config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root             'activities_metrics#index'
  resources :activities_metrics
  resources :metrics_targets

end

app/models/activities_metric.rb
class ActivitiesMetric < ActiveRecord::Base
end

app/models/metrics_target.rb
class MetricsTarget < ActiveRecord::Base
end

app/controllers/activities_metrics_controller.rb
class ActivitiesMetricsController < ApplicationController
  before_action :set_activities_metric, only: [:show, :edit, :update, :destroy]

  # GET /activities_metrics
  # GET /activities_metrics.json
  def index
    @activities_metrics = ActivitiesMetric.all
    File.open('activities_metrics.json', 'w') { |file| file.write(@activities_metrics.to_json) }
  end

  # GET /activities_metrics/1
  # GET /activities_metrics/1.json
  def show
  end

  # GET /activities_metrics/new
  def new
    @activities_metric = ActivitiesMetric.new
  end

  # GET /activities_metrics/1/edit
  def edit
  end

  # POST /activities_metrics
  # POST /activities_metrics.json
  def create
    @activities_metric = ActivitiesMetric.new(activities_metric_params)

    respond_to do |format|
      if @activities_metric.save
        format.html { redirect_to @activities_metric, notice: 'Activities metric was successfully created.' }
        format.json { render :show, status: :created, location: @activities_metric }
      else
        format.html { render :new }
        format.json { render json: @activities_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities_metrics/1
  # PATCH/PUT /activities_metrics/1.json
  def update
    respond_to do |format|
      if @activities_metric.update(activities_metric_params)
        format.html { redirect_to @activities_metric, notice: 'Activities metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @activities_metric }
      else
        format.html { render :edit }
        format.json { render json: @activities_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities_metrics/1
  # DELETE /activities_metrics/1.json
  def destroy
    @activities_metric.destroy
    respond_to do |format|
      format.html { redirect_to activities_metrics_url, notice: 'Activities metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activities_metric
      @activities_metric = ActivitiesMetric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activities_metric_params
      params.require(:activities_metric).permit(:activity, :week, :leads, :relevant_leads, :conversion, :time_spent, :max_time_client)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/metrics_targets_controller.rb
class MetricsTargetsController < ApplicationController
  before_action :set_metrics_target, only: [:show, :edit, :update, :destroy]

  # GET /metrics_targets
  # GET /metrics_targets.json
  def index
    @metrics_targets = MetricsTarget.all
    File.open('metrics_targets.json', 'w') { |file| file.write(@metrics_targets.to_json) }
  end

  # GET /metrics_targets/1
  # GET /metrics_targets/1.json
  def show
  end

  # GET /metrics_targets/new
  def new
    @metrics_target = MetricsTarget.new
  end

  # GET /metrics_targets/1/edit
  def edit
  end

  # POST /metrics_targets
  # POST /metrics_targets.json
  def create
    @metrics_target = MetricsTarget.new(metrics_target_params)

    respond_to do |format|
      if @metrics_target.save
        format.html { redirect_to @metrics_target, notice: 'Metrics target was successfully created.' }
        format.json { render :show, status: :created, location: @metrics_target }
      else
        format.html { render :new }
        format.json { render json: @metrics_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics_targets/1
  # PATCH/PUT /metrics_targets/1.json
  def update
    respond_to do |format|
      if @metrics_target.update(metrics_target_params)
        format.html { redirect_to @metrics_target, notice: 'Metrics target was successfully updated.' }
        format.json { render :show, status: :ok, location: @metrics_target }
      else
        format.html { render :edit }
        format.json { render json: @metrics_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics_targets/1
  # DELETE /metrics_targets/1.json
  def destroy
    @metrics_target.destroy
    respond_to do |format|
      format.html { redirect_to metrics_targets_url, notice: 'Metrics target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metrics_target
      @metrics_target = MetricsTarget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metrics_target_params
      params.require(:metrics_target).permit(:leads, :relevant_leads, :conversion, :time_spent, :max_time_client)
    end
end

app/helpers/activities_metrics_helper.rb
module ActivitiesMetricsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metrics_targets_helper.rb
module MetricsTargetsHelper
end

app/views/activities_metrics/_form.html.erb
<%= bootstrap_form_for(@activities_metric) do |f| %>
  <% if @activities_metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activities_metric.errors.count, "error") %> prohibited this activities_metric from being saved:</h2>

      <ul>
      <% @activities_metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :activity %>
  <%= f.number_field :week %>
  <%= f.number_field :leads %>
  <%= f.number_field :relevant_leads %>
  <%= f.number_field :conversion %>
  <%= f.number_field :time_spent %>
  <%= f.number_field :max_time_client %>
  <%= f.number_field :target %>
  <%= f.submit %>
<% end %>

app/views/activities_metrics/edit.html.erb
<div class="row">
   <div class="col-md-6 col-md-offset-1">
      <h2>Editing Activities Metric</h2>
      <%= render 'form' %>
   </div>
 </div>   

<%= link_to 'Show', @activities_metric %> |
<%= link_to 'Back', activities_metrics_path %>

app/views/activities_metrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities Metrics</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Activity</th>
      <th>Week</th>
      <th>Leads</th>
      <th>Relevant leads</th>
      <th>Conversion</th>
      <th>Time spent</th>
      <th>Max Time for Client</th>
      <th>KPI Target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities_metrics.each do |activities_metric| %>
      <tr>
        <td><%= activities_metric.activity %></td>
        <td><%= activities_metric.week %></td>
        <td><%= activities_metric.leads %></td>
        <td><%= activities_metric.relevant_leads %></td>
        <td><%= activities_metric.conversion %></td>
        <td><%= activities_metric.time_spent %></td>
        <td><%= activities_metric.max_time_client %></td>
        <td><%= activities_metric.target %></td>
        <td><%= link_to 'Show', activities_metric %></td>
        <td><%= link_to 'Edit', edit_activities_metric_path(activities_metric) %></td>
        <td><%= link_to 'Destroy', activities_metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weekly Report', new_activities_metric_path, class: "btn btn-default" %>
<%= link_to 'Dashboard', "dashing/dashboards/", class: "btn btn-info", style: "color: white" %>
<%= link_to 'Configure Targets', metrics_targets_path, class: "btn btn-danger", style: "color: white" %>

app/views/activities_metrics/new.html.erb
<div class="row">
   <div class="col-md-6 col-md-offset-1">
      <h2>New Activities Metric</h2>
      <%= render 'form' %>
   </div>
 </div>     

<%= link_to 'Back', activities_metrics_path %>

app/views/activities_metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @activities_metric.activity %>
</p>

<p>
  <strong>Week:</strong>
  <%= @activities_metric.week %>
</p>

<p>
  <strong>Leads:</strong>
  <%= @activities_metric.leads %>
</p>

<p>
  <strong>Relevant leads:</strong>
  <%= @activities_metric.relevant_leads %>
</p>

<p>
  <strong>Conversion:</strong>
  <%= @activities_metric.conversion %>
</p>

<p>
  <strong>Time spent:</strong>
  <%= @activities_metric.time_spent %>
</p>

<p>
  <strong>Max Time for Client:</strong>
  <%= @activities_metric.max_time_client %>
</p>

<p>
  <strong>Target:</strong>
  <%= @activities_metric.target %>
</p>

<%= link_to 'Edit', edit_activities_metric_path(@activities_metric) %> |
<%= link_to 'Back', activities_metrics_path %>

app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  My super sweet dashboard
<% end %>

<div id="summary" class="gridster">
  <h1><span style="text-align:center;"> KPI Summary </span></h1>
  <ul>
    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="Metrics Total" data-view="List" data-unordered="true" data-title="Metrics Total W<%= $current_week %>" data-moreinfo="# KPIs summarised among activities"></div>
    </li>
    <%= render partial: "layouts/dashing/metric_total", collection: $metrics, as: :metric %>    
  </ul>
</div>
<%= render partial: "layouts/dashing/activity", collection: $activities %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataInputForDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashing/_activity.html.erb
<!-- each activity on the separate row -->
 <!-- show activity metrics -->
<div class="gridster">
  <h1><span style="text-align:center;"> <%=activity%> </span></h1>
  <ul>
    <%= render partial: "layouts/dashing/activity_metric", collection: $metrics, locals:{activity: activity, index: activity_iteration.index}, as: :metric %>
  </ul>
</div>

<!--
<li data-row="<%= activity_iteration.index+1 %>" data-col="1" data-sizex="1" data-sizey="1">
    <%= render partial: "layouts/dashing/activity_metric_graph", collection: $metrics, locals:{activity: activity}, as: :metric %>
</li>
-->

app/views/layouts/dashing/_activity_metric.html.erb
<li data-row="<%= index+1 %>" data-col="1" data-sizex="1" data-sizey="1">
   <div data-id="<%= activity %> <%=metric%>" data-view="Number" data-title="<%=metric%>" data-moreinfo="Current Week vs Previous" data-prefix=""></div>
</li>

app/views/layouts/dashing/_activity_metric_graph.html.erb
<div data-id="<%= activity%> <%= metric%> Graph" data-view="Graph" data-title="<%= activity %> <%= metric %> Graph" style="background-color:#47bbb3;"></div>

app/views/layouts/dashing/_metric_total.html.erb
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
   <div id="total" data-id="<%=metric%> Total" data-view="Number" data-title="<%=metric%> total" data-moreinfo="Current Week vs Previous" data-prefix=""></div>
</li>
<% if $targets[0][metric] != 0 then %>
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
   <div id="total" data-id="<%=metric%> vs Target" data-view="Meter" data-title="<%=metric%> vs Target" data-height="200" data-width="200" data-min="0" data-max="100" data-suffix="%"></div>
</li>
<% end %>

app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= yield :title %></title>

    <%= javascript_include_tag 'dashing/application' %>
    <%= stylesheet_link_tag 'dashing/application' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="/favicon.ico">
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
      <div id="saving-instructions">
        <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
        <textarea id="gridster-code"></textarea>
      </div>
      <a href="#saving-instructions" id="save-gridster">Save this layout</a>
    <% end %>
  </body>
</html>

app/views/metrics_targets/_form.html.erb
<%= bootstrap_form_for(@metrics_target) do |f| %>
  <% if @metrics_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metrics_target.errors.count, "error") %> prohibited this metrics_target from being saved:</h2>

      <ul>
      <% @metrics_target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.number_field :leads, { label: "Leads in Total:" } %>
  <%= f.number_field :relevant_leads, { label: "Relevant Leads in Total:" } %>
  <%= f.number_field :conversion, { label: "Potential Customers in Total:" }  %>
  <%= f.number_field :time_spent, { label: "Time Spent in Total:" } %>
  <%= f.number_field :max_time_client, { label: "Maximum Time for a Single Client:" } %>
  <%= f.submit %>
<% end %>

app/views/metrics_targets/edit.html.erb
<div class="row">
   <div class="col-md-6 col-md-offset-1">
      <h2>Editing Metrics Targets</h2>
      <%= render 'form' %>
   </div>
 </div> 

<%= link_to 'Show', @metrics_target %> |
<%= link_to 'Back', metrics_targets_path %>

app/views/metrics_targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Metrics Targets</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Leads</th>
      <th>Relevant leads</th>
      <th>Conversion</th>
      <th>Time spent</th>
      <th>Max time client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics_targets.each do |metrics_target| %>
      <tr>
        <td><%= metrics_target.leads %></td>
        <td><%= metrics_target.relevant_leads %></td>
        <td><%= metrics_target.conversion %></td>
        <td><%= metrics_target.time_spent %></td>
        <td><%= metrics_target.max_time_client %></td>
        <td><%= link_to 'Show', metrics_target %></td>
        <td><%= link_to 'Edit', edit_metrics_target_path(metrics_target) %></td>
        <td><%= link_to 'Destroy', metrics_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metrics Target', new_metrics_target_path, class: "btn btn-default" %>

app/views/metrics_targets/new.html.erb
<div class="row">
   <div class="col-md-6 col-md-offset-1">
      <h2>New Metrics Targets</h2>
      <%= render 'form' %>
   </div>
 </div> 

<%= link_to 'Back', metrics_targets_path %>

app/views/metrics_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Leads:</strong>
  <%= @metrics_target.leads %>
</p>

<p>
  <strong>Relevant leads:</strong>
  <%= @metrics_target.relevant_leads %>
</p>

<p>
  <strong>Conversion:</strong>
  <%= @metrics_target.conversion %>
</p>

<p>
  <strong>Time spent:</strong>
  <%= @metrics_target.time_spent %>
</p>

<p>
  <strong>Max time client:</strong>
  <%= @metrics_target.max_time_client %>
</p>

<%= link_to 'Edit', edit_metrics_target_path(@metrics_target) %> |
<%= link_to 'Back', metrics_targets_path %>